src/Entity/Technique.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TechniqueRepository")
 */
class Technique
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nom;
    
    /**
     * @ORM\Column(type="float")
     */
    private $portions;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text")
     */
    private $progression;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $point_crit;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Allergenes", inversedBy="techniques")
     */
    private $allergenes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Classement", inversedBy="techniques")
     * @ORM\JoinColumn(nullable=false)
     */
    private $classement;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ingredient", mappedBy="recette", cascade={"persist"})
     */
    private $ingredients;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="boolean")
     */
    private $froid;

    public function __construct()
    {
        $this->allergenes = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->ingredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getProgression(): ?string
    {
        return $this->progression;
    }

    public function setProgression(string $progression): self
    {
        $this->progression = $progression;

        return $this;
    }

    public function getPointCrit(): ?string
    {
        return $this->point_crit;
    }

    public function setPointCrit(?string $point_crit): self
    {
        $this->point_crit = $point_crit;

        return $this;
    }

    /**
     * @return Collection|allergenes[]
     */
    public function getAllergenes(): Collection
    {
        return $this->allergenes;
    }

    public function addAllergene(allergenes $allergene): self
    {
        if (!$this->allergenes->contains($allergene)) {
            $this->allergenes[] = $allergene;
        }

        return $this;
    }

    public function removeAllergene(allergenes $allergene): self
    {
        if ($this->allergenes->contains($allergene)) {
            $this->allergenes->removeElement($allergene);
        }

        return $this;
    }

    public function getClassement(): ?Classement
    {
        return $this->classement;
    }

    public function setClassement(?Classement $classement): self
    {
        $this->classement = $classement;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPortions(): ?float
    {
        return $this->portions;
    }

    public function setPortions(?float $portions): self
    {
        $this->portions = $portions;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }


    /**
     * @return Collection|Ingredient[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
            $ingredient->setRecette($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        if ($this->ingredients->contains($ingredient)) {
            $this->ingredients->removeElement($ingredient);
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecette() === $this) {
                $ingredient->setRecette(null);
            }
        }

        return $this;
    }


    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFroid(): ?bool
    {
        return $this->froid;
    }

    public function setFroid(bool $froid): self
    {
        $this->froid = $froid;
        return $this;
    }

}

src/Form/TechniqueType.php
<?php

namespace App\Form;

use App\Entity\Classement;
use App\Entity\Allergenes;
use App\Entity\Technique;
use Doctrine\DBAL\Types\FloatType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class TechniqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class, array(
                'label' => 'Entrez un nom',
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'constraints' => array(
                    new NotBlank(array(
                        'message' => 'Le Nom ne peut pas etre vide !'
                    ))
                )))
            ->add('portions',TextType::class, array(
                'label' => 'Nombre de portions',
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'constraints' => array(
                    new NotBlank(array(
                        'message' => 'Le nombre de portions est obligatoire !'
                    ))
                )))
            ->add('description', TextareaType::class, [
                'required' => false,
                'label' => 'Description',
                'attr'=> array(
                    'class'=>'form-control'
                )
            ])
            ->add('image', FileType::class, array(
                'required' => false,
                'label' => 'Choisir une photo',
                'data_class' => null,
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'constraints' => [
                    new image ([
                        'mimeTypes' => [
                            'image/png', 'image/jpeg', 'image/gif'
                        ]
                    ])
                ]
            ))
            ->add('progression', TextareaType::class, [
                'required' => true,
                'label' => 'Progression',
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'constraints' => [
                    new NotBlank(array(
                        'message' => 'La progression est obligatoire !'
                    ))
                ]
            ])
            ->add('point_crit', TextareaType::class, [
                'required' => false,
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'label' => 'Point critique',
            ])
            ->add('allergenes', EntityType::class, array(
                'required' => false,
                'attr'=> array(
                    'class'=>'form-control selected3'
                ),
                'class' => Allergenes::class,
                'choice_label' => 'nom',
                'multiple' => true
                ))
            ->add('classement', EntityType::class, array(
                'class' => Classement::class,
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'choice_label' => 'nom'
                ))
            ->add('ingredients', CollectionType::class, array(
                'entry_type' => ProduitsTechniqueType::class,
                'attr'=> array(
                    'class'=>'col-12'
                ),
                'allow_add' => true,
                'allow_delete' => true
                ))
            ->add('froid', CheckboxType::class,array(
                'attr'=> array(
                    'class'=>'form-control'
                ),
                'label'=> 'Garder au froid?',
                'required' => false
                ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Technique::class,
        ]);
    }
}

src/Controller/TechniqueController.php
<?php

namespace App\Controller;

use App\Entity\Technique;
use App\Form\TechniqueType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/techniques", name="techniques_")
 */
class TechniqueController extends AbstractController
{
    /**
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(): Response
    {
        $technique = $this->getDoctrine()->getRepository(Technique::class)->findAll();       

        return $this->render('technique/index.html.twig', [
            'techniques' => $technique
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $technique = new Technique();
        $form = $this->createForm(TechniqueType::class, $technique);
        $form->handleRequest($request);

        // Validation formulaire
        if($form->isSubmitted() && $form->isValid()){

            $doctrine = $this->getDoctrine()->getManager();

            // ajouts de la photo
            if($technique->getImage()){
                $photo = $form->get('image')->getData();

                $nouveau_nom = md5(uniqid()).'.'.$photo->guessExtension();

                $photo->move(
                    $this->getParameter('fiches'),
                    $nouveau_nom
                );
                $technique->setImage($nouveau_nom);
            }
            $technique->setDate(new \DateTimeImmutable());

            // ajouts des des allergenes pour chaques ingrédient
            foreach($form->get('ingredients')->getData() as $ingredient) {
                $technique->addIngredient($ingredient);
                $ingredient->setRecette($technique);
                $produit=$ingredient->getProduits();
                foreach ($produit->getAllergenes() as $prodallergenes) {
                    $technique->addAllergene($prodallergenes);  
                }
            }
            // calcul du total
            $total=0;
            $ingredients=$technique->getIngredients();
            foreach ($ingredients as $ingredient ) {
                $total+= $ingredient->getProduits()->getPrix() * $ingredient->getQuantity();
            }
            
            $technique->setPrix($total);
            $doctrine->persist($technique);
            $doctrine->flush();

            $this->addFlash('success', 'Votre fiche technique à bien été crée !');

        return $this->redirectToRoute('techniques_index');
        }

        return $this->render('technique/new.html.twig', [
            'technique' => $technique,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Technique $technique): Response
    {
        return $this->render('technique/show.html.twig', [
            'technique' => $technique,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Technique $technique): Response
    {   
        //Sauvegarde ancienne photo
        $ancienne_photo=$technique->getImage();
        
        $form = $this->createForm(TechniqueType::class, $technique);
        $form->handleRequest($request);
       
        // Validation formulaire
        if ($form->isSubmitted() && $form->isValid()) {
            // edit de la photo
            if($technique->getImage()){
                if($ancienne_photo != null){
                    $filesystem = new Filesystem();
                    $filesystem->remove('upload/images/fiches/'.$ancienne_photo);
                }
                $photo = $form->get('image')->getData();

                $nouveau_nom = md5(uniqid()).'.'.$photo->guessExtension();

                $photo->move(
                    $this->getParameter('fiches'),
                    $nouveau_nom
                );
                $technique->setImage($nouveau_nom);
            }else{
                $technique->setImage($ancienne_photo);
            }
            $technique->setDate(new \DateTimeImmutable());

            // ajouts  des allergenes pour chaques ingrédient
            foreach($form->get('ingredients')->getData() as $ingredient) {
                $technique->addIngredient($ingredient);
                $ingredient->setRecette($technique);
                $produit=$ingredient->getProduits();
                foreach ($produit->getAllergenes() as $prodallergenes) {
                    $technique->addAllergene($prodallergenes);  
                }
            }

            // Calcul du prix total
            $total=0;
            $ingredients=$technique->getIngredients();
            foreach ($ingredients as $ingredient ) {
                $total+= $ingredient->getProduits()->getPrix() * $ingredient->getQuantity();
            }
            $technique->setPrix($total);

            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Votre fiche technique à bien été modifiée !');

            return $this->redirectToRoute('techniques_index');
        }

        return $this->render('technique/edit.html.twig', [
            'technique' => $technique,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/del/{id}", name="delete", methods={"DELETE"})
     */
    public function delete(Request $request, Technique $technique): Response
    {
        if ($this->isCsrfTokenValid('delete'.$technique->getId(), $request->request->get('_token'))) {
            // Suppr Image si il y a
            if($technique->getImage()){
            
                $filesystem = new Filesystem();
                $filesystem->remove('upload/images/fiches/'.$technique->getImage());
    
            }

            $entityManager = $this->getDoctrine()->getManager();

            // Suppr tout les ingredients de la technique
            foreach ($technique->getIngredients() as $ingredient) {
                $entityManager->remove($ingredient);
            }
            
            $entityManager->remove($technique);
            $entityManager->flush();

            $this->addFlash('success', 'Votre fiche technique à bien été supprimé !');
        }

        return $this->redirectToRoute('techniques_index');

    } 
}

templates/technique/_delete_form.html.twig
<form method="post" action="{{ path('techniques_delete', {'id': technique.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cette fiche technique ?');" class="d-inline m-0">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ technique.id) }}">
    <button class="btn btn-danger btn-sm mx-0">Supprimer</button>
</form>

templates/technique/_form.html.twig
<div class="container">
{{ form_start(form) }}
    {{ form_row(form.nom) }}
    {{ form_row(form.portions) }}
    {{ form_row(form.description) }}
    {{ form_row(form.image) }}
    {{ form_row(form.progression) }}
    {{ form_row(form.point_crit) }}
    {{ form_row(form.allergenes) }}
    {{ form_row(form.classement) }}
    {{ form_row(form.froid) }}
    <div id="ingredients" data-prototype="{{ form_widget(form.ingredients.vars.prototype)|e('html_attr' ) }}" class="row border p-3">
        <p class="col-12">Ingrédients<p>
        {{ form_widget(form.ingredients) }}
    </div>
    <button class="btn btn-success btn-sm  d-inline">{{ button_label|default('Sauvegarder') }}</button>
    <a href="{{ path('techniques_index') }}" class="btn btn-light btn-sm">Retour</a>

{{ form_end(form) }}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>

    $(function() {
        $('.selected2').select2({});
        $('.selected3').select2({
            multiple: 'true'
        });
        var $collectionHolder;

        // setup an "add a tag" link
        var $addTagButton = $('<button type="button" class="btn btn-dark">Ajouter un Produit</button>');
        var $newLink = $('<div class="col-3 mb-3"></div>').append($addTagButton);

        // Get the ul that holds the collection of tags
        $collectionHolder = $('#ingredients');

        // add the "add a tag" anchor and li to the tags ul
        $collectionHolder.append($newLink);

        // count the current form inputs we have (e.g. 2), use that as the new
        // index when inserting a new item (e.g. 2)
        $collectionHolder.data('index', $collectionHolder.find(':input').length);

        $addTagButton.on('click', function(e) {
            // add a new tag form (see next code block)
            addIngredientForm($collectionHolder, $newLink);
        });
    });


    function addIngredientForm($collectionHolder, $newLink) {
        // Get the data-prototype explained earlier
        var prototype = $collectionHolder.data('prototype');

        var newForm = prototype;
        // get the new index
        var index = $collectionHolder.data('index');

        newForm = newForm.replace(/__name__/g, index);

        // increase the index with one for the next item
        $collectionHolder.data('index', index + 1);

        // Display the form in the page in an li, before the "Add a tag" link li
        var $newFormSpan = $('<div class="col-3 mb-3"></div>').append(newForm);
        $newLink.before($newFormSpan);

        $('.selected2').select2({});

        addIngredientFormDeleteLink($newFormSpan)

    }

    function addIngredientFormDeleteLink($ingredientFormSpan) {
        var $removeFormButton = $('<button type="button" class="btn btn-danger">Delete</button>');
        $ingredientFormSpan.append($removeFormButton);

        $removeFormButton.on('click', function(e) {
            // remove the li for the tag form
            $ingredientFormSpan.remove();
        });
    }


</script>

templates/technique/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Fiche Technique{% endblock %}

{% block body %}
    <h1>Modifiez votre Fiche Technique</h1>

    {{ include('technique/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

    

    
{% endblock %}

templates/technique/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Technique index{% endblock %}

{% block body %}


    <h1>Technique</h1>
        {% for message in app.flashes('success') %}
            <div class="alert alert-success my-3">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('warning') %}
            <div class="alert alert-warning my-3">
                {{ message }}
            </div>
        {% endfor %}
    <a href="{{ path('index') }}" class="float-left btn btn-light btn-sm">Retour</a>
    <a href="{{ path('techniques_new') }}" class="float-right btn btn-info btn-sm">Nouveau</a>
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Nombre de portions</th>
                <th>Prix portions</th>
                <th>Prix total</th>
                <th>Classement</th> 
                <th>actions</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        {% for technique in techniques %}
            <tr>
                <td data-label="Nom">{{ technique.nom }}</td>
                <td data-label="Nombre de portions">{{ technique.portions }}</td>
                <td data-label="Prix portions">{{ (( technique.prix) / technique.portions)|round(2, 'floor') }} €</td>
                <td data-label="Prix total">{{ technique.prix}} €</td> 
                <td data-label="Classement">{{ technique.classement.nom }} </td> 
                <td data-label="actions">
                    <a href="{{ path('techniques_show', {'id': technique.id}) }}" class="btn btn-primary btn-sm">Détails</a>
                    <a href="{{ path('techniques_edit', {'id': technique.id}) }}" class="btn btn-secondary btn-sm">Modifier</a>
                    {{ include('technique/_delete_form.html.twig') }}
                <td data-label="Date">{{ technique.date|date('Y-m-d')}}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Aucun résultat trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/technique/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Fiche Technique{% endblock %}

{% block body %}
    <div class="container">       
    
        <h1>Ajouter une nouvelle fiche technique</h1>

        {{ include('technique/_form.html.twig') }}



{% endblock %}

templates/technique/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Technique{% endblock %}

{% block body %}

<div class="container card my-3 p-4">
    <div class="row justify-content-between">
        <span class="mx-3">{{technique.date|date('Y-m-d')}}</span>
    </div>
    <div class="row my-3">
        <div class="col-12">
            <h1 class="text-center mt-3">{{ technique.nom }}</h1>
        </div>
    </div>
    <div class="row my-3">
        <div class="col-8">
            <div class="row">
                <div class="col-6">
                    <p>Classement: {{ technique.classement.nom }}</p>
                    <p class="d-inline">Portions: {{ technique.portions }}</p>
                    <p>Froid :
                        {% if technique.froid == 1 %}
                            oui
                        {% else %}
                            non
                        {% endif %}
                    </p>
                </div>

                
                <div class="col-6">
                    <p class="d-inline">Cout portions : {{ ( technique.prix / technique.portions )|round(2, 'floor') }} €
                    </p>
                    <p>Cout total : {{technique.prix  }} € </p>
                </div>
            </div>


            {% if technique.image %}
            <div class="col-12">
                    <img src="{{asset('uploads/images/fiches/' ~ technique.image)}}" alt="technique.nom" id="image" class="">
                
            </div>
            {% endif %}
        </div>
        <div class="col-4">
            <h2>Allergènes:</h2>
            <p class="d-inline"> 
                {% for allergene in technique.allergenes %}
                        {{allergene.nom}} <br> 
                {% endfor %} 
            </p>
        </div>
    </div>    
    <div class="row my-3">
        <div class="col-12">
            <h3>Description :</h3>
            <p class="mx-3"> "{{ technique.description }} "</p>
        </div>
    </div>

    <div class="row my-3">
        <div class="col-6">
            <h3>Produits: </h3>
            <table>
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Unité</th>
                        <th>Quantités</th>
                        <th>Prix unitaire</th>
                        <th>Prix total</th>
                    </tr>
                </thead>
                <tbody>                   
                    {% for ingredient in technique.ingredients %}
                        <tr>
                            <td> {{ingredient.produits.nom}}</td>
                            <td> {{ingredient.produits.unite.nom}}</td>
                            <td> {{ingredient.Quantity}}</td>
                            <td> {{ingredient.produits.prix}} €</td>
                            <td> {{ingredient.produits.prix * ingredient.Quantity}} €</td>
                        </tr> 
                    {% endfor %}
                </tbody>
            </table>           
        </div>
        <div class="col-6">
            <h3>Progression: </h3>
            <p class="p-3">{{ technique.progression }}</p> 
        </div>
    </div>
    <div class="row my-3">
        <div class="col-12 border border-danger p-3">
            <h3 class="mt-0">Point critique: </h3>
            <p class="text-center">{{ technique.pointCrit }}</p>
        </div>
    </div>
</div>

<div class="container my-3">
    <div class="row justify-content-center"> 
        <div class="col-6 d-flex justify-content-around">     
            <a href="{{ path('techniques_index') }}" class="btn btn-info btn-sm mx-1">Retour</a>
            <a href="{{ path('techniques_edit', {'id': technique.id}) }}" class="btn btn-secondary btn-sm">Modifier</a>
            {{ include('technique/_delete_form.html.twig') }}
        </div>
    </div>
</div>


{% endblock %}